server:
  port: 8888

spring:
  application:
    name: damda-config

  cloud:
    config:
      server:
        git:
          uri: git@github.com:HyuckJuneHong/git-local-config.git
          ignoreLocalSshSettings: true
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIApv3LXFtHNXjxhNSMY5X86/o0bLnvu3Eqj5KD6qacT8oAoGCCqGSM49
            AwEHoUQDQgAEFhC028LT7Nor00kKF+2NGafQA4o3kKx9rP+bCjvwwRNKchgWLTO2
            6wZhlbGKZv/HkrgblvZpACn6GMnYqmvKNg==
            -----END EC PRIVATE KEY-----